# MADLIBS GAME 
adj1=input("enter an adjective: ")
adj2=input("enter a '--negative feeling--'adjective : ")
adj3=input("enter an adjective: ")
verb_ed=input("enter a verb ending with ed :")
pet=input("enter a pet ")
person=input("enter a person ")
place=input("enter a place (common noun) ")
obj=input("enter an object ")
print("--------------------------------------------------------------------")
print("It was a "+ adj1 + " ,cold November day .I woke up to the "+adj2+ " sounds of "+ person +" shouting. Done with my morning routine .")
print("There was a "+pet+" playing with my "+obj+" Suddenly it was tapperd was gifted by my "+person+"  on my birthday .")
print("Now i can't get back my "+obj+ ". The "+pet +" took that "+obj+ " to my "+person+" stood innocently! "+person +" forgived it .")
print("i took the "+pet+" to the "+place+" .We have "+verb_ed+" around . It was really an "+adj3+" day!") 
print("--------------------------------------------------------------------")