print("\n-------------- TUPLES -----------------\n")
# tuples are immutable unlike lists , we cannot modify the tuple
demo =(2,3,4,5)
print(demo)
print("\n-----------to access elements of a tuple in forward manner------------\n")
print(demo[0])
print(demo[1])
print(demo[2])
print(demo[3])
print("\n-----------to access elements of a tuple backwards------------\n")
print(demo[-1])
print(demo[-2])
print(demo[-3])
print(demo[-4])
print("\n-----------tuples are immutable------------\n")
# demo[1] = 0   ------->we acnnot change items of the tuple
# print(demo)
print("\n-----------List of tuples------------\n")
example=[(1,2),(2,3),(3,4)]  # ---------now this is a list ,all list operations (8.py file) can be done !!
coordinate=[(5,6),(7,8),(8,9)]
print(example[0])
print(example[-1])
example.remove((1,2))
print(example)
example.pop()
print(example)
example.extend(coordinate)
print(example)
example.insert(0,(0,1))
print(example)
example.append((9,10))
print(example)
print(example.index((5,6)))
example.append((0,1))
print(example)
print(example.count((0,1)))
print(example.count((3,4)))
example.sort()
print(example)
example.reverse()
print(example)
example2=coordinate.copy()
print("example2 = ",example2)