print("*    Hello World!!      *")
print("    _____________")
print("   ( ")
print("    \ ")
print("      \ ")
print("        \ ")
print("          \ ")
print("            \ ")
print("             ) ")
print("____________")
